[project]
org-name= "irushi"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    modules = ["load_yaml"]
    groupId = "org.yaml"
    artifactId = "snakeyaml"
    version = "1.25"
